
package lab8p2_jesusrodriguez;

import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Principal extends javax.swing.JFrame {

    private ArrayList<Nadadores> swimmers= new ArrayList();
    private ArrayList<Pais> Country= new ArrayList();
    private ArrayList<Evento> event= new ArrayList();
     AdP ap = new AdP("./PaisesParticipantes.lab");
    ADN an = new ADN("./Nadadores.lab");
    ADE ae = new ADE("./Eventos.lab");
    
 
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Record = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        CBNE1 = new javax.swing.JComboBox<>();
        CBNd1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        CBEV = new javax.swing.JComboBox<>();
        MODEV = new javax.swing.JButton();
        DELETEEVT = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Record1 = new javax.swing.JTextField();
        CBNE2 = new javax.swing.JComboBox<>();
        CBNd2 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        SwimmerName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CBN = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Age = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Height = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        RecordTime = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        MedalsIn = new javax.swing.JTextField();
        AddSwimmer = new javax.swing.JButton();
        CBNE = new javax.swing.JComboBox<>();
        CBNd = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        NameP = new javax.swing.JTextField();
        MedalsC = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ADDCOUNTRY = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        CMBE5 = new javax.swing.JComboBox<>();
        CMBN1 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        CMBN2 = new javax.swing.JComboBox<>();
        CMBN3 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        CBNE3 = new javax.swing.JComboBox<>();
        SwimmerName1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        CBNd3 = new javax.swing.JComboBox<>();
        Height1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Age1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        MedalsIn1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        RecordTime1 = new javax.swing.JTextField();
        CBNA = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        DELETEN = new javax.swing.JButton();
        MODN = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TablaL = new javax.swing.JButton();
        CBL = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 0, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel1.setText("Estilo");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 108, 41));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel2.setText("Distancia");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("Record");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        jPanel3.add(Record, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 160, -1));

        jButton1.setText("Crear Evento");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 300, 310));

        CBNE1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Pecho", "Dorso", "Mariposa", " " }));
        jPanel3.add(CBNE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, 30));

        CBNd1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "200", "400", "800", " " }));
        jPanel3.add(CBNd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 170, 30));

        jTabbedPane1.addTab("Crear Evento", jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 51, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CBEV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(CBEV, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 6, 266, 36));

        MODEV.setText("Modificar Evento");
        MODEV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MODEVMouseClicked(evt);
            }
        });
        jPanel2.add(MODEV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 267, 136));

        DELETEEVT.setText("Eliminar Evento");
        DELETEEVT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETEEVTMouseClicked(evt);
            }
        });
        jPanel2.add(DELETEEVT, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 267, 136));

        jLabel14.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel14.setText("Estilo");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 108, 41));

        jLabel15.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel15.setText("Distancia");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel16.setText("Record");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        jPanel2.add(Record1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 160, -1));

        CBNE2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Pecho", "Dorso", "Mariposa", " " }));
        CBNE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBNE2ActionPerformed(evt);
            }
        });
        jPanel2.add(CBNE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, 30));

        CBNd2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "200", "400", "800", " " }));
        jPanel2.add(CBNd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 170, 30));

        jTabbedPane1.addTab("Modificar/Eliminar Evento", jPanel2);

        jPanel4.setBackground(new java.awt.Color(51, 0, 153));

        jLabel4.setText("Nombre");

        jLabel5.setText("Nacionalidad");

        CBN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Edad");

        jLabel7.setText("Estatura");

        jLabel8.setText("Estilo");

        jLabel9.setText("Distancia");

        jLabel10.setText("Tiempo Record");

        jLabel11.setText("Medallas");

        AddSwimmer.setText("Agregar Nadador");
        AddSwimmer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddSwimmerMouseClicked(evt);
            }
        });

        CBNE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Pecho", "Dorso", "Mariposa", " " }));

        CBNd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "200", "400", "800", " " }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(CBNd, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(CBN, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addComponent(SwimmerName)
                                .addComponent(jLabel4)
                                .addComponent(Age)
                                .addComponent(Height)
                                .addComponent(CBNE, 0, 185, Short.MAX_VALUE))
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RecordTime, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(MedalsIn))
                                .addGap(118, 118, 118))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                                .addComponent(AddSwimmer, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SwimmerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBNE, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RecordTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MedalsIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AddSwimmer, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBNd, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(811, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Nadador", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));

        jLabel12.setBackground(new java.awt.Color(255, 102, 0));
        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setText("Nombre");

        jLabel13.setBackground(new java.awt.Color(255, 102, 0));
        jLabel13.setForeground(new java.awt.Color(255, 102, 0));
        jLabel13.setText("Medallas");

        ADDCOUNTRY.setText("AGREGAR PAIS");
        ADDCOUNTRY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADDCOUNTRYMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MedalsC, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameP, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ADDCOUNTRY, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ADDCOUNTRY, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NameP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MedalsC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(883, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Pais", jPanel5);

        jPanel8.setBackground(new java.awt.Color(102, 0, 102));

        jLabel21.setText("Nadador 1");

        jLabel26.setText("Nadador 2");

        jLabel27.setText("Nadador 3");

        jButton2.setText("Simular");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(CMBE5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel21))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel26))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel27))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(CMBN2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(CMBN1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(CMBN3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(CMBE5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CMBN1))
                .addGap(20, 20, 20)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CMBN2))
                .addGap(20, 20, 20)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jProgressBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CMBN3))
                .addGap(37, 37, 37)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(884, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Simulacion", jPanel8);

        jPanel6.setBackground(new java.awt.Color(153, 153, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CBNE3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Pecho", "Dorso", "Mariposa", " " }));
        jPanel6.add(CBNE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 185, -1));
        jPanel6.add(SwimmerName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 185, -1));

        jLabel17.setText("Distancia");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel18.setText("Estilo");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        CBNd3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "200", "400", "800", " " }));
        jPanel6.add(CBNd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 185, -1));
        jPanel6.add(Height1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 185, -1));

        jLabel19.setText("Estatura");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        jPanel6.add(Age1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 185, -1));

        jLabel20.setText("Edad");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel22.setText("Nadador");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        jPanel6.add(MedalsIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 102, 150, 20));

        jLabel23.setText("Medallas");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        jLabel24.setText("Tiempo Record");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));
        jPanel6.add(RecordTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 140, -1));

        CBNA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel6.add(CBNA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 180, -1));

        jLabel25.setText("Nombre");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        DELETEN.setText("Eliminar");
        DELETEN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETENMouseClicked(evt);
            }
        });
        jPanel6.add(DELETEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 220, 70));

        MODN.setText("Modificar");
        MODN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MODNMouseClicked(evt);
            }
        });
        jPanel6.add(MODN, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 220, 70));

        jTabbedPane1.addTab("Modificar/Eliminar Nadador", jPanel6);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Nacionalidad", "Edad", "Estatura", "Estilo", "Distancia", "Record", "Medallas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        TablaL.setText("Actualizar");
        TablaL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaLMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TablaL))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(CBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)
                        .addComponent(TablaL)))
                .addContainerGap(805, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar", jPanel9);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 630, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MODNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MODNMouseClicked
        String name= SwimmerName1.getText();
        
        int edad= Integer.parseInt(Age1.getText());
        double es= Double.parseDouble(Height1.getText());
        String Style= "";
        if (CBNE3.getSelectedIndex()==0) {
            Style= "Libre";
        } else if(CBNE3.getSelectedIndex()==1){
            Style= "Pecho";
        }else if(CBNE3.getSelectedIndex()==2){
            Style= "Dorso";
        }else if(CBNE3.getSelectedIndex()==3){
            Style="Mariposa";
        }
        int distance= 0;
        if (CBNd3.getSelectedIndex()==0) {
            distance=100;
        } else if(CBNd3.getSelectedIndex()==1){
            distance=200;
        }else if(CBNd3.getSelectedIndex()==2){
            distance=400;
        }else if(CBNd3.getSelectedIndex()==3){
            distance=800;
        }
        int rec= Integer.parseInt(RecordTime.getText());
        int medals= Integer.parseInt(MedalsIn.getText());
      
            swimmers.get(CBNA.getSelectedIndex()).setNombre(name);
            
            swimmers.get(CBNA.getSelectedIndex()).setEdad(edad);
            swimmers.get(CBNA.getSelectedIndex()).setHeight(es);
            swimmers.get(CBNA.getSelectedIndex()).setMedals(medals);
            swimmers.get(CBNA.getSelectedIndex()).setDis(distance);
            swimmers.get(CBNA.getSelectedIndex()).setNadar(Style);
            swimmers.get(CBNA.getSelectedIndex()).setRap(rec);
            
            binNad();
            JOptionPane.showMessageDialog(null, "Nadador Editado");
            SwimmerName1.setText("");
            Age1.setText("");
            Height1.setText("");

            RecordTime1.setText("");
            MedalsIn1.setText("");
            CBNA.setModel(updateComboboxN());
            CMBN1.setModel(updateComboboxN());
            CMBN2.setModel(updateComboboxN());
            CMBN3.setModel(updateComboboxN());
        
           
    }//GEN-LAST:event_MODNMouseClicked

    private void DELETENMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETENMouseClicked
        swimmers.remove(CBNA.getSelectedIndex());
        binNad();
        CBNA.setModel(updateComboboxN());
        CMBN1.setModel(updateComboboxN());
            CMBN2.setModel(updateComboboxN());
            CMBN3.setModel(updateComboboxN());
    }//GEN-LAST:event_DELETENMouseClicked

    private void ADDCOUNTRYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDCOUNTRYMouseClicked
        String namep= NameP.getText();
        int medalsp= Integer.parseInt(MedalsC.getText());
        Country.add(new Pais(namep,medalsp));
        binPais();
        NameP.setText("");
        MedalsC.setText("");
        JOptionPane.showMessageDialog(null, "Pais Agregado");
        CBN.setModel(updateComboboxC());
        CBL.setModel(updateComboboxC());
        ap.leerP();
        ap.add(new Pais(NameP.getText(), Integer.parseInt(MedalsC.getText())));
                ap.binNad();

    }//GEN-LAST:event_ADDCOUNTRYMouseClicked

    private void AddSwimmerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddSwimmerMouseClicked
        String name= SwimmerName.getText();
        Pais countries = Country.get(CBN.getSelectedIndex());
        int edad= Integer.parseInt(Age.getText());
        double es= Double.parseDouble(Height.getText());
        String Style= "";
        if (CBNE.getSelectedIndex()==0) {
            Style= "Libre";
        } else if(CBNE.getSelectedIndex()==1){
            Style= "Pecho";
        }else if(CBNE.getSelectedIndex()==2){
            Style= "Dorso";
        }else if(CBNE.getSelectedIndex()==3){
            Style="Mariposa";
        }
        int distance= 0;
        if (CBNd.getSelectedIndex()==0) {
            distance=100;
        } else if(CBNd.getSelectedIndex()==1){
            distance=200;
        }else if(CBNd.getSelectedIndex()==2){
            distance=400;
        }else if(CBNd.getSelectedIndex()==3){
            distance=800;
        }
        int rec= Integer.parseInt(RecordTime.getText());
        int medals= Integer.parseInt(MedalsIn.getText());
        if (countries.getNadador().size()<2) {
            countries.getNadador().add(new Nadadores(name,countries,edad,es,Style,distance,rec,medals));
            swimmers.add(new Nadadores(name,countries,edad,es,Style,distance,rec,medals));
           binNad();
            JOptionPane.showMessageDialog(null, "Nadador Agregado");
            SwimmerName.setText("");
            Age.setText("");
            Height.setText("");

            RecordTime.setText("");
            MedalsIn.setText("");
            CMBN1.setModel(updateComboboxN());
            CMBN2.setModel(updateComboboxN());
            CMBN3.setModel(updateComboboxN());
            CBNA.setModel(updateComboboxN());
            
             an.leerN();
                an.add(new Nadadores(name, countries, edad, es, Style, distance, rec, medals));
                an.binNad();
                ap.leerP();
                ap.getcountry().get(CBN.getSelectedIndex()).getNadador().add(new Nadadores(name, countries, edad, es, Style, distance, rec, medals));
                ap.binNad();
        }else{
            JOptionPane.showMessageDialog(null, "Ya esta lleno Pibe");
        }

    }//GEN-LAST:event_AddSwimmerMouseClicked

    private void DELETEEVTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEEVTMouseClicked
        event.remove(CBEV.getSelectedIndex());
        binEVT();
        CBEV.setModel(updateComboboxE());
        CMBE5.setModel(updateComboboxE());
    }//GEN-LAST:event_DELETEEVTMouseClicked

    private void MODEVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MODEVMouseClicked

        double record= Double.parseDouble(Record1.getText());

        int distance= 0;
        String Style= "";
        if (CBNE2.getSelectedIndex()==0) {
            Style= "Libre";
        } else if(CBNE2.getSelectedIndex()==1){
            Style= "Pecho";
        }else if(CBNE2.getSelectedIndex()==2){
            Style= "Dorso";
        }else if(CBNE2.getSelectedIndex()==3){
            Style="Mariposa";
        }

        if (CBNd2.getSelectedIndex()==0) {
            distance=100;
        } else if(CBNd2.getSelectedIndex()==1){
            distance=200;
        }else if(CBNd2.getSelectedIndex()==2){
            distance=400;
        }else if(CBNd2.getSelectedIndex()==3){
            distance=800;
        }
        event.get(CBEV.getSelectedIndex()).setDistancia(distance);
        event.get(CBEV.getSelectedIndex()).setEstilo(Style);
        event.get(CBEV.getSelectedIndex()).setRecord(record);
        binEVT();
        CBEV.setModel(updateComboboxE());
        CMBE5.setModel(updateComboboxE());
        JOptionPane.showMessageDialog(null, "Evento Modificado");
    }//GEN-LAST:event_MODEVMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String Style= "";
        if (CBNE1.getSelectedIndex()==0) {
            Style= "Libre";
        } else if(CBNE1.getSelectedIndex()==1){
            Style= "Pecho";
        }else if(CBNE1.getSelectedIndex()==2){
            Style= "Dorso";
        }else if(CBNE1.getSelectedIndex()==3){
            Style="Mariposa";
        }
        double record= Double.parseDouble(Record.getText());
        int distance= 0;
        if (CBNd1.getSelectedIndex()==0) {
            distance=100;
        } else if(CBNd.getSelectedIndex()==1){
            distance=200;
        }else if(CBNd.getSelectedIndex()==2){
            distance=400;
        }else if(CBNd.getSelectedIndex()==3){
            distance=800;
        }
        event.add(new Evento(Style,distance,record));
        binEVT();
        CBEV.setModel(updateComboboxE());
        CMBE5.setModel(updateComboboxE());
        JOptionPane.showMessageDialog(null, "Evento Creado");

        Record.setText("");

    }//GEN-LAST:event_jButton1MouseClicked

    private void CBNE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBNE2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBNE2ActionPerformed

    private void TablaLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaLMouseClicked
    jTable1.setModel(updateTableboxE());
    }//GEN-LAST:event_TablaLMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    
     public DefaultComboBoxModel updateComboboxC() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (Pais v : Country) {
            model.addElement(v);

        }
        return model;
    }

      public DefaultComboBoxModel updateComboboxN() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (Nadadores v : swimmers) {
            model.addElement(v);

        }
        return model;
    }
      
       public DefaultComboBoxModel updateComboboxE() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (Evento v : event) {
            model.addElement(v);

        }
        return model;
    }
       
       
        public DefaultTableModel updateTableboxE() {
            DefaultTableModel modl=new DefaultTableModel();
            
            
            
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Nacionalidad", "Edad", "Estatura", "Estilo", "Distancia", "Record", "Medallas"
            }
        ));
            modl= (DefaultTableModel) jTable1.getModel();
            Pais pais =Country.get(CBL.getSelectedIndex());
            for (Nadadores t : pais.getNadador()) {
                Object[] row = {t.getNombre(),t.getNacion(),t.getEdad(),t.getHeight(),t.getNadar(),t.getDis(),t.getRap(),t.getMedals()
                   
                };
    modl.addRow(row);}
            return modl;
        }
      
        
        public void binPais(){
            File archivo= new File("./Datos.pz");
            FileOutputStream fw = null;
        ObjectOutputStream bw = null;
        try {
            fw = new FileOutputStream(archivo);
            bw = new ObjectOutputStream(fw);
            for (Pais t : Country) {
                bw.writeObject(t);
            }
            bw.flush();
        } catch (Exception ex) {
        } finally {
            try {
                bw.close();
                fw.close();
            } catch (Exception ex) {
            }
        }
        }
        
        public void binNad(){
             File archivo= new File("./Datos.nad");
            FileOutputStream fw = null;
        ObjectOutputStream bw = null;
        try {
            fw = new FileOutputStream(archivo);
            bw = new ObjectOutputStream(fw);
            for (Nadadores t : swimmers) {
                bw.writeObject(t);
            }
            bw.flush();
        } catch (Exception ex) {
        } finally {
            try {
                bw.close();
                fw.close();
            } catch (Exception ex) {
            }
        }


      
        }
        
        public void binEVT(){
            File archivo= new File("./Datos.evt");
            FileOutputStream fw = null;
        ObjectOutputStream bw = null;
        try {
            fw = new FileOutputStream(archivo);
            bw = new ObjectOutputStream(fw);
            for ( Evento t : event) {
                bw.writeObject(t);
            }
            bw.flush();
        } catch (Exception ex) {
        } finally {
            try {
                bw.close();
                fw.close();
            } catch (Exception ex) {
            }
        } 
        }
        
        
        public void leerN(){
            try {            
            File ar= new File("./Datos.nad");
            Nadadores temp;
            if (ar.exists()) {
                FileInputStream entrada
                    = new FileInputStream(ar);
                ObjectInputStream objeto
                    = new ObjectInputStream(entrada);
                try {
                    while ((temp = (Nadadores) objeto.readObject()) != null) {
                        swimmers.add(temp);
                    }
                } catch (EOFException e) {
                    //encontro el final del archivo
                }
                objeto.close();
                entrada.close();
            }            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        }
        
         public void leerEVT(){
            try {            
            File ar= new File("./Datos.evt");
            Evento temp;
            if (ar.exists()) {
                FileInputStream entrada
                    = new FileInputStream(ar);
                ObjectInputStream objeto
                    = new ObjectInputStream(entrada);
                try {
                    while ((temp = (Evento) objeto.readObject()) != null) {
                        event.add(temp);
                    }
                } catch (EOFException e) {
                    //encontro el final del archivo
                }
                objeto.close();
                entrada.close();
            }            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
         }
          public void leerP(){
            try {            
            File ar= new File("./Datos.pz");
            Pais temp;
            if (ar.exists()) {
                FileInputStream entrada
                    = new FileInputStream(ar);
                ObjectInputStream objeto
                    = new ObjectInputStream(entrada);
                try {
                    while ((temp = (Pais) objeto.readObject()) != null) {
                        Country.add(temp);
                    }
                } catch (EOFException e) {
                    //encontro el final del archivo
                }
                objeto.close();
                entrada.close();
            }            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
          }
        
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDCOUNTRY;
    private javax.swing.JButton AddSwimmer;
    private javax.swing.JTextField Age;
    private javax.swing.JTextField Age1;
    private javax.swing.JComboBox<String> CBEV;
    private javax.swing.JComboBox<String> CBL;
    private javax.swing.JComboBox<String> CBN;
    private javax.swing.JComboBox<String> CBNA;
    private javax.swing.JComboBox<String> CBNE;
    private javax.swing.JComboBox<String> CBNE1;
    private javax.swing.JComboBox<String> CBNE2;
    private javax.swing.JComboBox<String> CBNE3;
    private javax.swing.JComboBox<String> CBNd;
    private javax.swing.JComboBox<String> CBNd1;
    private javax.swing.JComboBox<String> CBNd2;
    private javax.swing.JComboBox<String> CBNd3;
    private javax.swing.JComboBox<String> CMBE5;
    private javax.swing.JComboBox<String> CMBN1;
    private javax.swing.JComboBox<String> CMBN2;
    private javax.swing.JComboBox<String> CMBN3;
    private javax.swing.JButton DELETEEVT;
    private javax.swing.JButton DELETEN;
    private javax.swing.JTextField Height;
    private javax.swing.JTextField Height1;
    private javax.swing.JButton MODEV;
    private javax.swing.JButton MODN;
    private javax.swing.JTextField MedalsC;
    private javax.swing.JTextField MedalsIn;
    private javax.swing.JTextField MedalsIn1;
    private javax.swing.JTextField NameP;
    private javax.swing.JTextField Record;
    private javax.swing.JTextField Record1;
    private javax.swing.JTextField RecordTime;
    private javax.swing.JTextField RecordTime1;
    private javax.swing.JTextField SwimmerName;
    private javax.swing.JTextField SwimmerName1;
    private javax.swing.JButton TablaL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
